### PR TITLE
added my contribution- alarm_clock

### PR DESCRIPTION
**Pull request by mintera10**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please add the screenshot of clock to get it merged.
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄
👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
PR will be closed if screenshot not shared.
Please share it and get it merged.

**Comment by mintera10** [comment]
Sure I will add it by today 😀, I just request u time till afternoon as I'm
out..

**Comment by Ayu-hack** [comment]
okay

**Comment by Ayu-hack** [comment]
why you closed PR ? 
your project seems to be great. 
you just needed to add screenshot or video of working.

**Comment by mintera10** [comment]
I got confused so i created a new branch and updated all of this 🙈
Please check hehe

**Comment by Ayu-hack** [comment]
okay !

**Pull request closed without merging**
