### PR TITLE
Added University Management System

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Why did you added log folder, please real program or project.
Please share the screenshot of working, to get it merged.

**Comment by LeViiAcKerMan01** [comment]
Screenshot 2024-10-06 225713

UMS Project is fully working...You can check it out yourself!!
Should i remove that crawler log folder program, it is a problem on leetcode though??

**Comment by LeViiAcKerMan01** [comment]
I am sorry, i pushed crawler_log_folder.cpp to some folder unknowingly... 
Removed it finally , could this be merged now..?

**Comment by Ayu-hack** [comment]
There is no code file present. Please fix it or PR will be closed.

**Comment by LeViiAcKerMan01** [comment]
My bad wait a min..
lemme fix it..

**Comment by LeViiAcKerMan01** [comment]
How about now??
Is the issue fixed..i guess it is..

**Comment by Ayu-hack** [comment]
🎉 Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos to stay updated for next year’s Hacktoberfest!

**Comment by LeViiAcKerMan01** [comment]
Thnc alot man

**Comment by Ayu-hack** [comment]
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by LeViiAcKerMan01** [comment]
Hey @Ayu-hack why the repos are being excluded from hactoberfest...

**Comment by Ayu-hack** [comment]
no it is not excluded. Please the share screenshot

**Comment by LeViiAcKerMan01** [comment]
Screenshot_20241007-114123_Chrome

Take a look at this...

**Comment by Ayu-hack** [comment]
yeah buddy. I saw someone did false report against repo. I have mailed to support it will resolve soon.

**Comment by Ayu-hack** [comment]
I will update you. If not then you can contribute to other one. Really sorry .

**Comment by LeViiAcKerMan01** [comment]
> yeah buddy. I saw someone did false report against repo. I have mailed to support it will resolve soon.

thats what i was talking about....
Will it be resolved anytime soon...
Thnc for the reply anyway @Ayu-hack , appreciated...

**Pull request merged**
