### PR TITLE
Create dijkstra.cpp

### PR DESCRIPTION
**Pull request by nirajanacharya**
Dijkstra's algorithm finds the shortest path from a source node to all other nodes in a weighted graph. It uses a priority queue for efficient edge relaxation and distance updates.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by nirajanacharya** [comment]
why your repo is not included in the hacktoberfest 2024??

[image: image.png]







Kindly regards,

*Nirajan Acharya *

Full-stack Developer

<https://github.com/NirajanAcharya666>
<https://www.linkedin.com/in/nirajanacharya/>

**Comment by Ayu-hack** [comment]
no

**Comment by nirajanacharya** [comment]
I have send you the proof. Why it is happening so?







Kindly regards,

*Nirajan Acharya *

Full-stack Developer

https://nirajanacharya.com.np/

<https://github.com/NirajanAcharya666>
<https://www.linkedin.com/in/nirajanacharya/>

**Comment by Ayu-hack** [comment]
which proof buddy?

**Pull request closed without merging**
