### PR TITLE
Alarm clock on CLI

### PR DESCRIPTION
**Pull request by mintera10**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
- Please share the working video or screenshot of project here ! 
- So that I can merged it. 

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by mintera10** [comment]
I did share the ss ?

**Comment by Ayu-hack** [comment]
no I cant see any screenshot or video here.
use comment section and insert the video

**Comment by mintera10** [comment]
https://github.com/user-attachments/assets/cdeb59a4-1717-4189-a066-eb3753be84b9

**Comment by mintera10** [comment]
is this ok?

**Comment by Ayu-hack** [comment]
**Merged.** 
You should contribute in more. **Check on my** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) a post contains all the link of repo.

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by mintera10** [comment]
Thank you :D

**Pull request merged**
