### PR TITLE
Added solution for Real Time Stock Price Tracker Using Sorted List in Python 

### PR DESCRIPTION
**Pull request by pratikj697**
The goal is to design a system that tracks stock prices in real-time. We need to perform the following operations efficiently:

1. Insert new stock prices.
2. Retrieve the minimum stock price.
3. Retrieve the maximum stock price.
4. Retrieve the median stock price.

Issue #45

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Merged. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by pratikj697** [comment]
@Ayu-hack can you please provide me some repos where i can make pull request because my all other pull request get excluded.

**Comment by Ayu-hack** [comment]
Check my [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) , here you find a post which has all the repos links. 


More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by pratikj697** [comment]
Why it's get excluded.

**Comment by Ayu-hack** [comment]
no buddy it didn't got excluded. Please share the screenshot.

**Comment by pratikj697** [comment]
IMG_20241007_150845
Its get excluded Today.

**Pull request merged**
