### PR TITLE
Create Lexical_Analyzer.c

### PR DESCRIPTION
**Pull request by kunal15112001**
Implemented Lexical Analyser in C

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please the working screenshot or video, then only I can merge it

**Comment by kunal15112001** [comment]
IMG_20241005_000628

**Comment by Ayu-hack** [comment]
Compiler should.be installed on your PC itself.

**Comment by Ayu-hack** [comment]
PR will be closed due to no response and invalid.

**Comment by kunal15112001** [comment]
Wait I will Update it by Today.

**Comment by Ayu-hack** [comment]
okay. Update ASAP

**Comment by Ayu-hack** [comment]
PR will be closed today. If not update by today evening.

**Comment by Ayu-hack** [comment]
DUE TO NO RESPONSE THE PR HAS BEEN CLOSED.

**Pull request closed without merging**
