### PR TITLE
Implement GCD calculation using brute force, Euclidean, and binary me…

### PR DESCRIPTION
**Pull request by prajwaln07**
### Description
This pull request introduces a C++ program that implements three different approaches for calculating the Greatest Common Divisor (GCD) of two integers. The purpose is to showcase various algorithms with different time complexities and demonstrate best coding practices.

### Changes Made
- **Brute Force Method**: A straightforward approach that checks all integers up to the minimum of the two numbers to find the largest integer that divides both.
- **Euclidean Algorithm**: An optimized method that significantly reduces iterations by using the principle that GCD(a, b) = GCD(b, a % b).
- **Binary GCD Algorithm (Stein's Algorithm)**: The most efficient method that utilizes binary operations for enhanced performance.

### File(s) Added
- `gcd_calculator.cpp`: Contains the implementation of all three GCD calculation methods along with a `main` function to test their outputs.

### Benefits
- This implementation provides a clear comparison of algorithmic efficiency and practical application in solving the GCD problem.
- It adheres to standard coding practices with meaningful variable names, comments, and structured code for better readability.

### Testing
The program includes a `main` function that tests the GCD methods with the numbers 36 and 60. The outputs for all three approaches are displayed to verify correctness.

### Future Work
- Consider adding more test cases for various pairs of integers to further validate the implementations.
- Potentially extend the program to handle negative integers and edge cases.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by prajwaln07** [comment]
> Please share the screenshot of working, to get it merged.

@Ayu-hack 
05 10 2024_14 17 54_REC

**Comment by Ayu-hack** [comment]
Online complier won't work. You need run on your PC complier.

**Comment by prajwaln07** [comment]
> Online complier won't work. You need run on your PC complier.

@Ayu-hack 
ssgcd

**Comment by Ayu-hack** [comment]
Great !
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Pull request merged**
