### PR TITLE
Chatbot Project

### PR DESCRIPTION
**Pull request by DevDatir**
Hi @Ayu-hack I have this is the PR I have created for #68 

description
description

This is how the project looks like so far, we can add more queries to this chatbot!

Also, I am trying to add the frontend to this project, this is the initial version. Meanwhile please merge these changes!
Thanks

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Is this chatbot is powered by AI API or you have entered limited set of queries?

**Comment by DevDatir** [comment]
Yes, I have used an AI-powered API (specifically the Cohere API) but is also designed to handle specific predefined queries about college information based on my dataset

**Comment by Ayu-hack** [comment]
- Please share working video of project and ask some questions in which it uses AI.
- It will merged. 
- Ask your friends to participate in hacktoberfest and share these repo with them

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by DevDatir** [comment]
https://github.com/user-attachments/assets/e0f91acf-d62d-48b2-880d-d169ef7e0989

@Ayu-hack Please find this working video of the updated project
Changes made -->

1. AI Explanation for Best College: The chatbot now generates AI-based explanations for the query "Which college is best?", providing dynamic reasons based on ratings, placements, and cutoffs.
2. Handling Open-Ended Queries: With the handle_general_questions() function, the chatbot can now process natural-language questions like "Tell me about college life" or "What are the best branches to study?".
3. AI-Generated Responses: The chatbot no longer relies solely on pre-defined answers, instead using AI to generate informative responses based on common knowledge of Rajasthan engineering colleges.
4. Improved Query Parsing: The parse_user_input() function is enhanced to better understand terms related to cutoffs, fees, placements, and more, making it effective for both structured and unstructured queries.

I hope you are satisfied with the changes I made.

**Comment by Ayu-hack** [comment]
- Great Work! 
- Amazing Project. Keep enhancing it.
- Merged.

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
If you any your friend do PR in my repos please them to share your name or username as refer, for sure their PR will be merged faster. 
you should also contribute to more repos. Check my linkedin their you will find post containing links of all repos of hacktoberfest.

**Comment by DevDatir** [comment]
Ya, I'll definitely share this repo with my friends and thanks for accepting my work!

**Pull request merged**
