### PR TITLE
Solving n queens problem in Ruby programming language #94

### PR DESCRIPTION
**Pull request by Ayushi40804**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by Ayushi40804** [comment]
n_queen
0feb">

**Comment by Ayu-hack** [comment]
Great !
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts! 🙌

**Pull request merged**
