### PR TITLE
Basic Weather App 

### PR DESCRIPTION
**Pull request by ananyag309**
Basic Weather App (Using Open Weather Map API) #19

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please add screenshots of working app to get it merged

**Comment by Ayu-hack** [comment]
PR will be closed if screenshot not shared. 
Please share it and get it merged.

**Comment by ananyag309** [comment]
@Ayu-hack i am sorry for replying late i am quite busy with college exam will share the ss asap

**Comment by Ayu-hack** [comment]
No worries. Take your time. 

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Pull request closed without merging**
