### PR TITLE
Submitted implementation of deque in CPP.

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged. 
⭐ Star this repos to get your PR merged faster! 🚀

**Comment by LeViiAcKerMan01** [comment]
Screenshot 2024-10-06 223215

Already starred and the program is working aswell!!
Rest of all other programs on pointers are working correctly as i have checked them before while working with them..

**Comment by Ayu-hack** [comment]
Please delete problem on pointer folder. It is of no use buddy.

**Comment by LeViiAcKerMan01** [comment]
> Please delete problem on pointer folder. It is of no use buddy.

wait a minute ..

**Comment by LeViiAcKerMan01** [comment]
> > Please delete problem on pointer folder. It is of no use buddy.
> 
> wait a minute ..

done..

**Comment by LeViiAcKerMan01** [comment]
Can i add one more PR to this repository as  most of them are being excluded.. dunno why!!

**Comment by Ayu-hack** [comment]
Yes can add. Even more repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
🎉 Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos to stay updated for next year’s Hacktoberfest!**

**Comment by LeViiAcKerMan01** [comment]
Thnc man....really!!

**Comment by Ayu-hack** [comment]
Your Welcome!
Please add something advance or unique program or project buddy.

**Comment by LeViiAcKerMan01** [comment]
> Your Welcome! Please add something advance or unique program or project buddy.

kk wait , how about a university management system written in cpp?

**Pull request merged**
