### PR TITLE
Implementation of Stack using Array , Dynamic Array & Linked List

### PR DESCRIPTION
**Pull request by kishan-25**
### Description:
This includes the implementation of the Stack data structure in C++ using three different underlying structures: Static Array, Dynamic Array, and Linked List. Each implementation follows the LIFO (Last In, First Out) principle and showcases key stack operations.

**1. Stack using Static Array:**
A fixed-size stack implementation using a static array.
Operations implemented:
Push: Adds an element to the top of the stack (fails if the stack is full).
Pop: Removes the top element (fails if the stack is empty).
Peek/Top: Returns the top element without removing it.
isEmpty: Checks if the stack is empty.
isFull: Checks if the stack is full (since the size is fixed).
Constraints: Stack size must be predefined, and it cannot grow beyond the allocated memory.
**2. Stack using Dynamic Array:**
A resizable stack implementation using a dynamic array that grows and shrinks as needed.
Operations implemented:
Push: Adds an element to the top of the stack. The array resizes dynamically when full (usually doubles in size).
Pop: Removes the top element (fails if the stack is empty).
Peek/Top: Returns the top element without removing it.
Resize: Dynamically adjusts the size of the array based on the stack’s usage (increasing and decreasing memory when necessary).
isEmpty: Checks if the stack is empty.
Benefits: More flexible in terms of memory usage compared to a static array, but with a slight overhead for resizing.
**3. Stack using Linked List:**
A dynamic memory implementation where each element is a node in a linked list.
Operations implemented:
Push: Adds a new node to the top of the stack (the head of the linked list).
Pop: Removes the top node (fails if the stack is empty).
Peek/Top: Returns the value of the top node without removing it.
isEmpty: Checks if the stack is empty.
Advantages: Efficient memory usage with no predefined size, ideal for cases where the number of elements is unknown or constantly changing.
**Purpose:**
The purpose of this pull request is to demonstrate the flexibility of stack implementations using different data structures and provide a comparative analysis of performance and memory management across:

Fixed-size (Static Array).
Resizable (Dynamic Array).
Dynamic memory allocation (Linked List).
**Testing:**
Each implementation has been tested for edge cases such as pushing into a full stack, popping from an empty stack, and handling dynamic resizing.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by kishan-25** [comment]
Images added & plz review once and let me know if you need further changes . 
Thank you accepting my pull request .

**Comment by Ayu-hack** [comment]
Please the share the screenshot.

**Comment by kishan-25** [comment]
array
Dynamicarray
Linkedlist

Also added up in the STACK folder  and shared on your gmail .

**Comment by kishan-25** [comment]
@Ayu-hack Sir can you plz specify me the location to upload the screenshot.

**Comment by Ayu-hack** [comment]
Here only in comments section like you have shared above.

**Comment by Ayu-hack** [comment]
Great !
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Pull request merged**
