### PR TITLE
added  Hangman Game with ASCII Art

### PR DESCRIPTION
**Pull request by ananyag309**
#80 
Hangman Game with ASCII Art
A fun command-line version of the classic Hangman game with ASCII art. You can play this right from the terminal.

e2
e1

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great! 
I can see that you have added two files, but there is an irrelevant file included named "weather.py."

**Comment by Ayu-hack** [comment]
You may make Pull request of weather app separately.

**Comment by ananyag309** [comment]
@Ayu-hack done changes

**Comment by Ayu-hack** [comment]
Great! 
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

**Comment by Ayu-hack** [comment]
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Congratulations! 🎉 
You’re the top committer in this repository with a total of 9 commits! 
🚀💻 Keep up the amazing work! 👏

**Pull request merged**
