### PR TITLE
unique password generator using python

### PR DESCRIPTION
**Pull request by Ankitmohanty2**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
- Please share the working video of project. 
- Add a readme file with main file.

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ankitmohanty2** [comment]
ok adding wait

**Comment by Ankitmohanty2** [comment]
https://github.com/user-attachments/assets/24ba9c59-2dfe-49d5-aa23-ba01de07ed63


added done

**Comment by Ayu-hack** [comment]
- Great Work! 
- Merged.
- You should make PRs in repo.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ankitmohanty2** [comment]
thank you

**Comment by Ankitmohanty2** [comment]
bro that contribution got excluded can u add this as label hacktoberfest-accepted?

**Comment by Ayu-hack** [comment]
bro the tag is already there.

**Comment by Ankitmohanty2** [comment]
but bro in hacktober fest page its showing excluded

**Pull request merged**
