### PR TITLE
Added picross

### PR DESCRIPTION
**Pull request by Aditijainnn**
picross
picross game #24

### CODE REVIEW

**Comment by Ayu-hack** [comment]
please add more working screenshot or video of project. 
Project name is bit irrelevant. Try to change.
It will be merged as changes are made. 

There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
Should I close it or you are doing the changes?

**Comment by Aditijainnn** [comment]
> Should I close it or you are doing the changes?

no i am changing it

**Comment by Ayu-hack** [comment]
okay then please share the more screenshots of it.

**Pull request closed without merging**
