### PR TITLE
Create MergeSort.cpp

### PR DESCRIPTION
**Pull request by yatikakain**
Added merge Sort program

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged. ⭐ Star this repos to get your PR merged faster! 🚀

**Comment by yatikakain** [comment]
> Please share the screenshot of working, to get it merged. ⭐ Star this repos to get your PR merged faster! 🚀

{080373AF-A5E0-4ADF-8A84-D6FDE6981B0B}
Attached Screenshot for working code

**Comment by yatikakain** [comment]
Also added Rock Paper Scissor Game
{599C5302-A88A-4CBC-90A7-41BF9B6D347F}

**Comment by Ayu-hack** [comment]
Please delete Rock Paper Scissor Game it already exists.

**Comment by yatikakain** [comment]
Deleted

**Comment by Ayu-hack** [comment]
🎉 Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos to stay updated for next year’s Hacktoberfest!**

**Pull request merged**
