### PR TITLE
Moore_voting_algo.cpp with working screenshot

### PR DESCRIPTION
**Pull request by MPrathamjain**
Screenshot (58)

thank you for guiding me. I have shared the screenshot and stared this repo. Please guide me is anything more is required. I am new to git, or open source and still experimenting with different buttons. thank for guidance .

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working screenshot, to get it merged.

**Comment by MPrathamjain** [comment]
I added the code for moore voting algorithm and I also  shared the screenshot  of the output  in above msg . I add it again .
Screenshot (58)
Or do you mean anything else by working screenshot. Thank you for you help.

**Comment by Ayu-hack** [comment]
Good!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos to stay updated for next year’s Hacktoberfest!**

**Comment by Ayu-hack** [comment]
More enhancement needed.

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts! 🙌

**Pull request merged**
